"""

Revision ID: b638621daa16
Revises: d93f9f0d20d7
Create Date: 2018-03-16 12:19:32.993655

"""

# revision identifiers, used by Alembic.
revision = 'b638621daa16'
down_revision = 'd93f9f0d20d7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from app import db
from app.models import Analytic

class AnalyticOld(db.Model):
  __tablename__ = 'analytics'
  __table_args__ = {'extend_existing': True}
  kind = db.Column(db.Integer, primary_key=True, default=0)

def upgrade():
    for analytic in db.session.query(AnalyticOld).all():
        if analytic.kind != 1:
            db.session.delete(analytic)
    db.session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'kind')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('kind', mysql.TINYINT(display_width=4), server_default=sa.text(u'0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
