"""

Revision ID: efcd3338922a
Revises: 8b9568c9734b
Create Date: 2018-04-03 11:05:06.127743

"""

# revision identifiers, used by Alembic.
revision = 'efcd3338922a'
down_revision = '8b9568c9734b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.alter_column('firmware', 'inhibit_download',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_analyst',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_vendor_manager',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('vendors', 'visible',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('vendors', 'visible_for_search',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'visible_for_search',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('vendors', 'visible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_vendor_manager',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_analyst',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column('firmware', 'inhibit_download',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text(u'0'))
